### ISSUE TITLE
Ryan Opel -- CS631 Website

### ISSUE THREAD

**Issue by opelr** [apreshill/data-vis-labs-2018#3]
https://ryan-opel-cs-631.netlify.com/

https://gitlab.com/opelr/ohsu-cs-631-static-site

**Comment by apreshill** [comment]
Hey @opelr could you post rendered link too? Great presentation today!

**Comment by opelr** [comment]
Edited - thanks @apreshill!

**Comment by apreshill** [comment]
Hey- thinking more about this, it might be slightly different data wrangling involved, but I wonder if your plot would work if you changed the y-axis to % of hours per day in use? You could chop up time into 24 hour periods, then calculate 24 minus # of idle hours. You may have already tried an iteration of this- if so, don't mind me! (I'm not suggesting you have to update anything at this point, just a suggestion!).

**Comment by opelr** [comment]
I did think of taking the plot in that direction at one point, but never looked into it much -- I'll give that a try this weekend! 

Ultimately, my worry that long rides would be given too much weight steered me in the other direction, but perhaps that was misguided. Thanks for the feedback!

**Comment by apreshill** [comment]
https://twitter.com/apreshill/status/1014531288689045505
