### ISSUE TITLE
Lawley - CS 631 Final Project Site & Repo

### ISSUE THREAD

**Issue by gracelawley** [apreshill/data-vis-labs-2018#4]
https://gracelawley-cs631.netlify.com/

https://github.com/gracelawley/cs631-final-project

**Comment by apreshill** [comment]
Leave me your twitter handle 👍

**Comment by gracelawley** [comment]
@apreshill I changed it to graceolawley!

**Comment by apreshill** [comment]
https://twitter.com/apreshill/status/1014531302937092097
