### ISSUE TITLE
salem CS631 site

### ISSUE THREAD

**Issue by alexandrasalem** [apreshill/data-vis-labs-2018#5]
https://alexsalem.netlify.com/

https://github.com/alexandrasalem

**Comment by apreshill** [comment]
hey @alexandrasalem do you have a twitter handle?

**Comment by apreshill** [comment]
https://twitter.com/apreshill/status/1014531306091266048

**Comment by alexandrasalem** [comment]
I don't! But maybe I should get one... :)
